# Generated by Django 6.1 on 2026-09-14 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=150)),
                ('nivel_interes', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('presupuesto', models.IntegerField()),
                ('resultado', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=300)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
